/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Christopher
 */
public class urbano_NN extends javax.swing.JFrame {

    /**
     * Creates new form urbano_NN
     */
    public urbano_NN() {
        initComponents();
                this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        añadir1 = new javax.swing.JButton();
        añadir2 = new javax.swing.JButton();
        añadir3 = new javax.swing.JButton();
        talla1 = new javax.swing.JComboBox<>();
        talla2 = new javax.swing.JComboBox<>();
        talla3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cooper Black", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprasNN.PNG"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        añadir1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        añadir1.setText("añadir");
        añadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir1ActionPerformed(evt);
            }
        });
        getContentPane().add(añadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 100, 40));

        añadir2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        añadir2.setText("añadir");
        añadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir2ActionPerformed(evt);
            }
        });
        getContentPane().add(añadir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 110, 40));

        añadir3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        añadir3.setText("añadir");
        añadir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir3ActionPerformed(evt);
            }
        });
        getContentPane().add(añadir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 90, 40));

        talla1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "talla", "39", "40", "41", "42", "43" }));
        getContentPane().add(talla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 90, 30));

        talla2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "talla", "39", "40", "41", "42", "43" }));
        getContentPane().add(talla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 90, 30));

        talla3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "talla", "39", "40", "41", "42", "43" }));
        getContentPane().add(talla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_niños.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 370, 120));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido a Urbano");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("REGRESAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compraH.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 883, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_añadir1ActionPerformed

    private void añadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_añadir2ActionPerformed

    private void añadir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_añadir3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        compra_NN ko=new compra_NN();
        this.dispose();
        ko.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urbano_NN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urbano_NN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urbano_NN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urbano_NN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urbano_NN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadir1;
    private javax.swing.JButton añadir2;
    private javax.swing.JButton añadir3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> talla1;
    private javax.swing.JComboBox<String> talla2;
    private javax.swing.JComboBox<String> talla3;
    // End of variables declaration//GEN-END:variables
}
