/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author Christopher
 */
public class variedad extends javax.swing.JFrame {

    /**
     * Creates new form variedad
     */
    public variedad() {
        initComponents();
                this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        informacion = new javax.swing.JButton();
        AYUDA = new javax.swing.JButton();
        COMPRA = new javax.swing.JButton();
        salida = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido a King Monkey ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 680, 60));

        informacion.setBackground(new java.awt.Color(255, 51, 51));
        informacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        informacion.setForeground(new java.awt.Color(0, 0, 0));
        informacion.setText("INFORMACION DE LA EMPRESA");
        informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionActionPerformed(evt);
            }
        });
        getContentPane().add(informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 50));

        AYUDA.setBackground(new java.awt.Color(255, 102, 102));
        AYUDA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AYUDA.setForeground(new java.awt.Color(0, 0, 0));
        AYUDA.setText("AYUDA");
        AYUDA.setToolTipText("");
        getContentPane().add(AYUDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 300, 50));

        COMPRA.setBackground(new java.awt.Color(255, 51, 51));
        COMPRA.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        COMPRA.setForeground(new java.awt.Color(0, 0, 0));
        COMPRA.setText("COMPRAR");
        COMPRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPRAActionPerformed(evt);
            }
        });
        getContentPane().add(COMPRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 300, 70));

        salida.setBackground(new java.awt.Color(0, 102, 102));
        salida.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        salida.setForeground(new java.awt.Color(255, 255, 255));
        salida.setText("SALIR ");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        getContentPane().add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 170, -1));

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_variedad-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 410, 360));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("¿Que es lo que necesita?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        fondo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fondo2.setForeground(new java.awt.Color(255, 255, 255));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/variedad.PNG"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 883, 545));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionActionPerformed
        infoEmpresa ent = new infoEmpresa();
        ent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_informacionActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
         JOptionPane.showMessageDialog(null, "gracias por comprar en KING MONKEY");
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void COMPRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPRAActionPerformed
        compras og=new compras();
        og.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_COMPRAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(variedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(variedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(variedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(variedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new variedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AYUDA;
    private javax.swing.JButton COMPRA;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton salida;
    // End of variables declaration//GEN-END:variables
}
